### ISSUE TITLE
RESET already declared for Portenta H7

### ISSUE THREAD

**Issue by gbr1** [arduino-libraries/ArduinoMotorCarrier#29]
It is not possible to use this library with Portenta because RESET is already declared in STM32 mbed core used by Arduino.

In this library is used at:
https://github.com/arduino-libraries/ArduinoMotorCarrier/blob/e0e8051057c60cfaafe6cf20b1b42332fcf1e65b/src/Common.h#L19

**Comment by aentinger** [comment]
Fixed, see #40 .
