### ISSUE TITLE
usage from other Arduino boards

### ISSUE THREAD

**Issue by gbr1** [arduino-libraries/ArduinoMotorCarrier#31]
Hi! Due issue #29 I'm trying to use Arduino DUE. I connected I2C and SPI but it seems impossible to use.
I run test firmware but says that the carrier is not recognizable. Red led was not blinking.
When I try to flash a new firmware by using flasher, output is only 4096 and 70 and stuck in upload loop.

Is it MKR locked?
Thank you in advance!

**Comment by aentinger** [comment]
This library is only supported on `samd` and `mbed_portenta`.
