### ISSUE TITLE
Add support for Portenta H7

### ISSUE THREAD

**Issue by aliphys** [arduino-libraries/ArduinoMotorCarrier#40]
Please add support for the Portenta H7 in the library. 

---

As disucssed with @Rocketct , the MKR Motor Carrier is hardware compatible with the Portenta H7.

> ok so this means that the problem [hardware incompatibility] doesn't exist

_Originally posted by @Rocketct in https://github.com/arduino-libraries/ArduinoMotorCarrier/issues/36#issuecomment-893283648_

See _RESET already declared for Portenta H7_ #29

**Comment by per1234** [comment]
Closing as resolved by https://github.com/arduino-libraries/ArduinoMotorCarrier/pull/44
