### ISSUE TITLE
How to build the Firmware for SAMD11 ?

### ISSUE THREAD

**Issue by KjellMorgenstern** [arduino-libraries/ArduinoMotorCarrier#8]
Hello,

I'd like to experiment with the SAMD11 on the MKRMotorShield, for example a configurable deadzone compensation. Or exporting the stop() and run() methods. Or syncing two motors.

For this, it would be quite helpful to modify and compile the D11-Firmware. I found https://github.com/mattairtech/ArduinoCore-samd , but I think this is not the right board support. At least I was not able to compile the  D11-Firmware for the targets provided by https://www.mattairtech.com/software/arduino/package_MattairTech_index.json

From this code comment, it looks like there is a specific board manager support url.
`// compile me with target mkrmotorshield:samd:mkrmotorshield:bootloader=0kb,pinmap=complete,lto=disabled during development
`

Do you use a mkrmotorshield target for the board manager? If so, could you make it available or point me to it?

**Comment by facchinm** [comment]
Hi @KjellMorgenstern ,
sorry for the long delay, I totally missed this issue.
I just pushed the core files (based on mattairtech's core) on https://github.com/arduino/ArduinoCore-samd/tree/mkrmotorcarrier .
You still need mattairtech's core to be installed via board manager to grab the right tools.
There's currently a bug on that core that prevents using LTO with any published toolchain, so I'm using ArchLinux one to correctly produce the "production" binary.
If you want to debug and have an SWD programmer (like Atmel ICE) you can select "LTO off + no bootloader" and compile with any toolchain

**Comment by aentinger** [comment]
Closing this issue, as it has been some time.
